### ISSUE TITLE
Still getting this LUA error (number expected, got nil)

### ISSUE THREAD

**Issue by Clisty1973** [jordonwow/bigdebuffs#547] opened 2022-12-30 21:39 UTC
Message: Interface/FrameXML/CompactUnitFrame.lua:1488: bad argument #2 to 'min' (number expected, got nil)
Time: Fri Dec 30 21:35:47 2022
Count: 310
Stack: Interface/FrameXML/CompactUnitFrame.lua:1488: bad argument #2 to 'min' (number expected, got nil)
[string "=[C]"]: in function `min'
[string "@Interface/FrameXML/CompactUnitFrame.lua"]:1488: in function <Interface/FrameXML/CompactUnitFrame.lua:1461>
[string "@Interface/AddOns/BigDebuffs/BigDebuffs.lua"]:2047: in function `ShowBigDebuffs'
[string "@Interface/AddOns/BigDebuffs/BigDebuffs.lua"]:1693: in function <Interface/AddOns/BigDebuffs/BigDebuffs.lua:1544>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface/FrameXML/CompactUnitFrame.lua"]:96: in function <Interface/FrameXML/CompactUnitFrame.lua:47>

Locals: (*temporary) = 26.999990
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by Nelythia** [comment] 2022-12-30 22:48
Because it was fixed in a pull request that wasn't merged by the author yet, so this is a spam duplicate of your previously posted issue

**Comment by Clisty1973** [comment] 2022-12-31 11:34
thank you for answering. Much appreciated

**Closed** 2022-12-31 20:24 UTC
